### ISSUE TITLE
Feature request: Option for "keeping width"

### ISSUE THREAD

**Issue by surmvoise** [littlebusters/Resize-Artboard-to-Fit-Contents#1]
I'd love to see an option to keep the width (without defining a specific amount) while resizing the height to fit the content.

**Comment by littlebusters** [comment]
@surmvoise This feature was added! I sent a review to Adobe.
If you want to use it immediately, download it from [here](https://github.com/littlebusters/Resize-Artboard-to-Fit-Contents/releases/tag/1.2.0).
