### ISSUE TITLE
Bounding box on component issue

### ISSUE THREAD

**Issue by pavlito** [littlebusters/Resize-Artboard-to-Fit-Contents#2]
Hi, 

First of all, thanks for creating this very useful plugin.
It was working fine until some of XD lastest updates.

In the newest version of XD - when defining a component with shadow bounding **box is added**.
I am providing an example of a project where I am using a header with shadow.
Using your plugin with this new bounding box features resize top of the artboard, and that is the problem.

Recalculating artboard size by reducing by the top or bottom bounding box size could be a solution. 
Adding a couple of checkboxes or switches into settings screen can help users to choose how the calculations are done.

Let me know if you need more info. Thanks

![Isse with shadow](https://snipboard.io/1a2J3q.jpg)

**Comment by littlebusters** [comment]
@pavlito Thanks feature request!

I'm using ver.22.7.12.3 in Japanese.
I seems a component bounding box not include drop shadow bounding. Could you like show me to component structure of the uploaded picture?

**Comment by pavlito** [comment]
@littlebusters here is my skype pavle_lucic

**Comment by littlebusters** [comment]
Sorry for the late reply.
Do you mean that is there an object over the drop shadow?

**Comment by pavlito** [comment]
No worries. 

Seems like xd bug. When reopening document - bounding seems ok...

**Comment by littlebusters** [comment]
I'm glad. Close it.
