### ISSUE TITLE
Feature Request: Resize content to fit artboard

### ISSUE THREAD

**Issue by velara3** [littlebusters/Resize-Artboard-to-Fit-Contents#3]
Hi! I really enjoy the plugin! :) I would like to see the option to resize an item to fit the artboard. 

For example, a user adds an image to their artboard that is larger than the artboard. They want to make the image fit inside the artboard. He selects the image and chooses "Size to fit artboard" from the plugin menu. The large image is resized down to fit inside the artboard.

**Comment by littlebusters** [comment]
@velara3 Hi!
Do you want this feature?
https://github.com/craigmdennis/adobe-xd-fit-to-parent
